package com.chylee.fxiaoke.core.mapper;

import com.chylee.fxiaoke.core.model.QrtzJob;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface QrtzJobMapper {

    List<QrtzJob> list(Integer id, String name);

    @Select("select count(*) from qrtz_job")
    int selectCount();

    List<QrtzJob> listPage(@Param("offset") Integer offset, @Param("pageSize") Integer pageSize);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    int insert(QrtzJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    int insertSelective(QrtzJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    QrtzJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    int updateByPrimaryKeySelective(QrtzJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    int updateByPrimaryKey(QrtzJob record);
}