package com.chylee.fxiaoke.core.model;

import java.util.Date;

public class QrtzJob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.id
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.job_group
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.job_name
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.job_desc
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String jobDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.bean
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String bean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.params
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String params;

    private String childIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.status
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.create_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.update_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public QrtzJob(Integer id, String jobGroup, String jobName, String jobDesc, String bean, String params, String childIds, Byte status, Date createTime, Date updateTime) {
        this.id = id;
        this.jobGroup = jobGroup;
        this.jobName = jobName;
        this.jobDesc = jobDesc;
        this.bean = bean;
        this.params = params;
        this.childIds = childIds;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public QrtzJob() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.id
     *
     * @return the value of qrtz_job.id
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.id
     *
     * @param id the value for qrtz_job.id
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.job_group
     *
     * @return the value of qrtz_job.job_group
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.job_group
     *
     * @param jobGroup the value for qrtz_job.job_group
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.job_name
     *
     * @return the value of qrtz_job.job_name
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.job_name
     *
     * @param jobName the value for qrtz_job.job_name
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.job_desc
     *
     * @return the value of qrtz_job.job_desc
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.job_desc
     *
     * @param jobDesc the value for qrtz_job.job_desc
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc == null ? null : jobDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.bean
     *
     * @return the value of qrtz_job.bean
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getBean() {
        return bean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.bean
     *
     * @param bean the value for qrtz_job.bean
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setBean(String bean) {
        this.bean = bean == null ? null : bean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.params
     *
     * @return the value of qrtz_job.params
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.params
     *
     * @param params the value for qrtz_job.params
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    public String getChildIds() {
        return childIds;
    }

    public void setChildIds(String childIds) {
        this.childIds = childIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.status
     *
     * @return the value of qrtz_job.status
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.status
     *
     * @param status the value for qrtz_job.status
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.create_time
     *
     * @return the value of qrtz_job.create_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.create_time
     *
     * @param createTime the value for qrtz_job.create_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job.update_time
     *
     * @return the value of qrtz_job.update_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job.update_time
     *
     * @param updateTime the value for qrtz_job.update_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}