package com.chylee.fxiaoke.core.model;

import java.util.Date;

public class QrtzTrigger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.id
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.trigger_group
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String triggerGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.trigger_name
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String triggerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.cron_expression
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.time_interval
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Integer timeInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job.trigger_id
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Integer jobId;

    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.status
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.create_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_trigger.update_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_trigger
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public QrtzTrigger(Integer id, String triggerGroup, String triggerName, String cronExpression, Integer timeInterval,
                       Integer jobId, String jobName, Byte status, Date createTime, Date updateTime) {
        this.id = id;
        this.triggerGroup = triggerGroup;
        this.triggerName = triggerName;
        this.cronExpression = cronExpression;
        this.timeInterval = timeInterval;
        this.jobId = jobId;
        this.jobName = jobName;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_trigger
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public QrtzTrigger() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.id
     *
     * @return the value of qrtz_trigger.id
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.id
     *
     * @param id the value for qrtz_trigger.id
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.trigger_group
     *
     * @return the value of qrtz_trigger.trigger_group
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.trigger_group
     *
     * @param triggerGroup the value for qrtz_trigger.trigger_group
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.trigger_name
     *
     * @return the value of qrtz_trigger.trigger_name
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.trigger_name
     *
     * @param triggerName the value for qrtz_trigger.trigger_name
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName == null ? null : triggerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.cron_expression
     *
     * @return the value of qrtz_trigger.cron_expression
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.cron_expression
     *
     * @param cronExpression the value for qrtz_trigger.cron_expression
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.time_interval
     *
     * @return the value of qrtz_trigger.time_interval
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Integer getTimeInterval() {
        return timeInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.time_interval
     *
     * @param timeInterval the value for qrtz_trigger.time_interval
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setTimeInterval(Integer timeInterval) {
        this.timeInterval = timeInterval;
    }

    public Integer getJobId() {
        return jobId;
    }

    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.status
     *
     * @return the value of qrtz_trigger.status
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.status
     *
     * @param status the value for qrtz_trigger.status
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.create_time
     *
     * @return the value of qrtz_trigger.create_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.create_time
     *
     * @param createTime the value for qrtz_trigger.create_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_trigger.update_time
     *
     * @return the value of qrtz_trigger.update_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_trigger.update_time
     *
     * @param updateTime the value for qrtz_trigger.update_time
     *
     * @mbg.generated Thu Nov 28 17:10:09 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}